name = "Skeet Pack"
author = "Kepler Sticka-Jones <kepler@stickajones.org>"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c567e61f73f91ef9d2c72e0ffd1b1552d5536532728fc28f553c566967b29236"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
