name = "Skeet Pack"
author = "Kepler Sticka-Jones <kepler@stickajones.org>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e40a69dea6f6018b213e4e796db5fcd8f729ce9b4ade7b55a3c562bb877565c0"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
