name = "Skeet Pack"
author = "Kepler Sticka-Jones <kepler@stickajones.org>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64e9875b5ae9687837c142daf00da424e92ae8e96393063fcb4fd8e7ccb3e386"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
